# Generated by Django 5.2 on 2025-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="est_valide",
            field=models.BooleanField(default=False),
        ),
    ]
