# Generated by Django 5.2 on 2025-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="couleur",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="intensite",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="mode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="musique",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="etat",
            field=models.CharField(default="éteint", max_length=100),
        ),
    ]
