# Generated by Django 5.2 on 2025-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets", "0002_objetconnecte_couleur_objetconnecte_intensite_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objetconnecte",
            old_name="marque",
            new_name="position",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="batterie",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="connectivite",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="description",
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="mode",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
