# Generated by Django 5.2 on 2025-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets", "0003_rename_marque_objetconnecte_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="mode_auto",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
