# Generated by Django 5.2 on 2025-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets", "0004_objetconnecte_mode_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="mode_lit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
