# Generated by Django 5.2 on 2025-04-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets", "0005_objetconnecte_mode_lit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objetconnecte",
            name="mode_auto",
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="couleur",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="date_derniere_interaction",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="etat",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="mode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="mode_lit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="musique",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="position",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="type_objet",
            field=models.CharField(
                choices=[
                    ("lumière", "Lumière"),
                    ("télévision", "Télévision"),
                    ("enceinte", "Enceinte Intelligente"),
                    ("thermostat", "Thermostat"),
                    ("grille-pain", "Grille-pain"),
                    ("réfrigérateur", "Réfrigérateur"),
                    ("détecteur de fumée", "Détecteur de fumée"),
                    ("volet", "Volet roulant"),
                    ("store", "Store"),
                    ("lit", "Lit connecté"),
                    ("douche", "Douche intelligente"),
                    ("miroir", "Miroir connecté"),
                    ("diffuseur", "Diffuseur d’air"),
                    ("clé wifi", "Clé Wi-Fi"),
                    ("parasol", "Parasol"),
                    ("capteur eau", "Capteur d’eau"),
                ],
                max_length=50,
            ),
        ),
    ]
