# Generated by Django 5.2 on 2025-04-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets", "0006_remove_objetconnecte_mode_auto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objetconnecte",
            old_name="mode",
            new_name="mode_thermostat",
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="etat",
            field=models.CharField(default="éteint", max_length=100),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="intensite",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="mode_lit",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="type_objet",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="volume",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
