# Generated by Django 5.2 on 2025-04-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets", "0007_rename_mode_objetconnecte_mode_thermostat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objetconnecte",
            name="mode_lit",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="mode_thermostat",
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="consommation_eau",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
